name: Laravel

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: php
        with:
          php-version: "8.3"
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');" cp .env.test

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test

      - name: Run migrations (for testing)
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: :memory
        run: php artisan migrate --force --seed
      - name: Test phpstan
        run: ./vendor/bin/phpstan analyse
      - name: Test Unit
        run: ./vendor/bin/phpunit
